/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package club.sport;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohammed
 */
public class JFrameSport extends javax.swing.JFrame {

    /**
     * Creates new form JFrameSport
     */
    public JFrameSport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nom = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pren = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        date = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        paiement = new javax.swing.JTextPane();
        ajot = new java.awt.Button();
        effacer = new java.awt.Button();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        age = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        email = new javax.swing.JTextPane();
        tsprt = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        hsprt = new javax.swing.JComboBox<>();
        ville = new javax.swing.JComboBox<>();
        quitter = new java.awt.Button();
        sexe = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        tel = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();

        jScrollPane3.setViewportView(jTextPane1);

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nom");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jScrollPane1.setViewportView(nom);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, 30));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Prénom ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 50, -1));

        jScrollPane2.setViewportView(pren);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 160, 30));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sexe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 30, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adresse");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 50, -1));

        jLabel6.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date de naissance");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, -1));

        jScrollPane7.setViewportView(date);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 160, 30));

        jScrollPane8.setViewportView(address);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 160, 30));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Téléphone");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 60, -1));

        jLabel13.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Type de sport");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 80, -1));

        jLabel14.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Heure du sport");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 90, -1));

        jLabel16.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Paiement");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 60, -1));

        jScrollPane15.setViewportView(paiement);

        getContentPane().add(jScrollPane15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 240, 160, 30));

        ajot.setBackground(new java.awt.Color(0, 90, 162));
        ajot.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ajot.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        ajot.setForeground(new java.awt.Color(255, 255, 255));
        ajot.setLabel("Ajouter");
        ajot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajotActionPerformed(evt);
            }
        });
        getContentPane().add(ajot, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 80, 30));

        effacer.setBackground(new java.awt.Color(0, 90, 162));
        effacer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        effacer.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        effacer.setForeground(new java.awt.Color(255, 255, 255));
        effacer.setLabel("Effacer");
        effacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                effacerActionPerformed(evt);
            }
        });
        getContentPane().add(effacer, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 80, 30));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Club de Sport");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 290, 60));

        jLabel17.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Age");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 30, -1));

        jScrollPane16.setViewportView(age);

        getContentPane().add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 160, 30));

        jLabel19.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Ville");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 30, -1));

        jLabel20.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Email");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jScrollPane18.setViewportView(email);

        getContentPane().add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 160, 30));

        tsprt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(tsprt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 160, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 1120, 270));

        hsprt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        hsprt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsprtActionPerformed(evt);
            }
        });
        getContentPane().add(hsprt, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, 160, -1));

        ville.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ville, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 120, 160, -1));

        quitter.setActionCommand("spr");
        quitter.setBackground(new java.awt.Color(0, 90, 162));
        quitter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        quitter.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        quitter.setForeground(new java.awt.Color(255, 255, 255));
        quitter.setLabel("Quitter");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        getContentPane().add(quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 80, 30));

        sexe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexeeActionPerformed(evt);
            }
        });
        getContentPane().add(sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        jScrollPane9.setViewportView(tel);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 160, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/club/sport/SL_043021_42650_02.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -30, -1, 710));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        sexe.removeAllItems();
        sexe.addItem("choisir...");
        sexe.addItem("Homme");
        sexe.addItem("Famille");
        
        tsprt.removeAllItems();
        tsprt.addItem("choisir...");
        tsprt.addItem("Musculation");
        tsprt.addItem("Football");
        tsprt.addItem("Tenis");
        tsprt.addItem("Basketball");
        tsprt.addItem("Box");
        tsprt.addItem("Yoga-Plates");
        tsprt.addItem("Gym");
        tsprt.addItem("Coach Sportif");
        tsprt.addItem("Golf");
        
        hsprt.removeAllItems();
        hsprt.addItem("choisir...");
        hsprt.addItem("7:00 AM to 2:00 PM");
        hsprt.addItem("4:00 PM to 12:00 AM");
 
        
        ville.removeAllItems();
        ville.addItem("choisir...");
        ville.addItem("CASABLANCA");
        ville.addItem("AGADIR");
        ville.addItem("MARRAKECH");
        ville.addItem("RABAT");
        ville.addItem("TANGER");
        ville.addItem("EL JADIDA");
        ville.addItem("SALÉ");
        ville.addItem("KENITRA");
        ville.addItem("MOHAMMEDIA");
        table.setModel(m);
        String t[] = {"Nom","Prénom","Sexe","Age","Email","Téléphone","Date de naissance","Adresse","Ville","Type de sport","Heure du sport","Paiement"};
        m.setColumnIdentifiers(t);
    }//GEN-LAST:event_formWindowOpened

    private void hsprtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsprtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hsprtActionPerformed

    private void sexeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexeeActionPerformed

    private void ajotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajotActionPerformed
        // TODO add your handling code here:
      
        String n = nom.getText();
        String p = pren.getText();       
        String s = sexe.getSelectedItem().toString();
        String a = age.getText();
        String e  = email.getText();
        String te = tel.getText();
        String d =  date.getText();
        String ad = address.getText();
        String v =  ville.getSelectedItem().toString();
        String ts=  tsprt.getSelectedItem().toString();
        String hs=  hsprt.getSelectedItem().toString();
        String pa=  paiement.getText();
        
        

        String t[] = {n,p,s,a,e,te,d,ad,v,ts,hs,pa};
        m.addRow(t);
        nom.setText("");
        pren.setText("");
        age.setText("");
    }//GEN-LAST:event_ajotActionPerformed

    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Voulez-vous quitter?","Quitter",JOptionPane.YES_NO_OPTION);
        
        if (a== JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_quitterActionPerformed

    private void effacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_effacerActionPerformed
        // TODO add your handling code here:

        int a = table.getSelectedRow();

        if (a == -1)return;

        m.removeRow(a);

    }//GEN-LAST:event_effacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameSport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameSport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane address;
    private javax.swing.JTextPane age;
    private java.awt.Button ajot;
    private javax.swing.JTextPane date;
    private java.awt.Button effacer;
    private javax.swing.JTextPane email;
    private javax.swing.JComboBox<String> hsprt;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane nom;
    private javax.swing.JTextPane paiement;
    private javax.swing.JTextPane pren;
    private java.awt.Button quitter;
    private javax.swing.JComboBox<String> sexe;
    private javax.swing.JTable table;
    private javax.swing.JTextPane tel;
    private javax.swing.JComboBox<String> tsprt;
    private javax.swing.JComboBox<String> ville;
    // End of variables declaration//GEN-END:variables
 DefaultTableModel m = new DefaultTableModel();
}
